# Generated by Django 3.1.2 on 2020-11-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Workout',
        ),
    ]
