# Generated by Django 3.1.2 on 2020-11-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0002_auto_20201126_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
