# Generated by Django 3.1.2 on 2020-11-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0003_workout_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('user_name', models.TextField(blank=True)),
            ],
        ),
    ]
