# Generated by Django 3.1.2 on 2020-11-30 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_bro.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_bro.user')),
            ],
        ),
    ]
