# Generated by Django 3.1.2 on 2020-12-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0005_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='reps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='sets',
            field=models.TextField(blank=True),
        ),
    ]
