# Generated by Django 3.1.2 on 2020-12-01 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0006_auto_20201201_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
