# Generated by Django 3.1.2 on 2020-12-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_bro', '0007_program_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='reps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='sets',
            field=models.IntegerField(blank=True),
        ),
    ]
