# Generated by Django 3.1.2 on 2020-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0002_statusmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
